export interface CreateObjectTypeOption {
  value: string;
  label: string;
}

export const CREATE_OBJECT_TYPE_OPTIONS: CreateObjectTypeOption[] = [
  { value: "TABLE", label: "Table" },
  { value: "VIEW", label: "View" },
  { value: "PROCEDURE", label: "Procedure" },
  { value: "FUNCTION", label: "Function" },
  { value: "PACKAGE", label: "Package" },
  { value: "PACKAGE BODY", label: "Package Body" },
  { value: "TRIGGER", label: "Trigger" },
  { value: "SEQUENCE", label: "Sequence" },
  { value: "TYPE", label: "Type" },
  { value: "SYNONYM", label: "Synonym" },
];

const CREATE_OBJECT_TYPE_SET = new Set(
  CREATE_OBJECT_TYPE_OPTIONS.map((option) => option.value),
);
const DEFAULT_OBJECT_NAME_BY_TYPE: Record<string, string> = {
  TABLE: "NEW_TABLE",
  VIEW: "NEW_VIEW",
  PROCEDURE: "NEW_PROCEDURE",
  FUNCTION: "NEW_FUNCTION",
  PACKAGE: "NEW_PACKAGE",
  "PACKAGE BODY": "NEW_PACKAGE",
  TRIGGER: "NEW_TRIGGER",
  SEQUENCE: "NEW_SEQUENCE",
  TYPE: "NEW_TYPE",
  SYNONYM: "NEW_SYNONYM",
};

interface BuildCreateObjectTemplateInput {
  schema: string;
  objectType: string;
  objectName: string;
}

function toQuotedIdentifier(value: string): string {
  return `"${value.replace(/"/g, '""')}"`;
}

function normalizeOracleIdentifier(value: string, fallback: string): string {
  const normalized = value
    .trim()
    .toUpperCase()
    .replace(/[^A-Z0-9_$#]/g, "_")
    .replace(/^([^A-Z_])/, "_$1");
  return normalized.length > 0 ? normalized : fallback;
}

export function normalizeCreateObjectType(value: string): string | null {
  const normalized = value.trim().toUpperCase();
  return CREATE_OBJECT_TYPE_SET.has(normalized) ? normalized : null;
}

export function createObjectDefaultName(objectType: string): string {
  const normalizedType = normalizeCreateObjectType(objectType);
  if (!normalizedType) {
    return "NEW_OBJECT";
  }
  return DEFAULT_OBJECT_NAME_BY_TYPE[normalizedType] ?? "NEW_OBJECT";
}

export function normalizeCreateObjectName(
  objectType: string,
  objectName: string,
): string {
  const fallback = createObjectDefaultName(objectType);
  return normalizeOracleIdentifier(objectName, fallback);
}

export function buildCreateObjectTemplate(
  input: BuildCreateObjectTemplateInput,
): string {
  const objectType = normalizeCreateObjectType(input.objectType);
  if (!objectType) {
    throw new Error(`Unsupported object type: ${input.objectType}`);
  }

  const schema = normalizeOracleIdentifier(input.schema, "APP");
  const objectName = normalizeCreateObjectName(objectType, input.objectName);
  const qualifiedName = `${toQuotedIdentifier(schema)}.${toQuotedIdentifier(objectName)}`;

  if (objectType === "TABLE") {
    return `create table ${qualifiedName} (
  id number generated by default as identity primary key,
  created_at timestamp default current_timestamp not null
);`;
  }

  if (objectType === "VIEW") {
    return `create or replace view ${qualifiedName} as
select
  1 as sample_column
from dual;`;
  }

  if (objectType === "PROCEDURE") {
    return `create or replace procedure ${qualifiedName} as
begin
  null;
end;
/`;
  }

  if (objectType === "FUNCTION") {
    return `create or replace function ${qualifiedName}
return number
as
begin
  return 0;
end;
/`;
  }

  if (objectType === "PACKAGE") {
    return `create or replace package ${qualifiedName} as
  procedure run;
end ${toQuotedIdentifier(objectName)};
/`;
  }

  if (objectType === "PACKAGE BODY") {
    return `create or replace package body ${qualifiedName} as
  procedure run is
  begin
    null;
  end run;
end ${toQuotedIdentifier(objectName)};
/`;
  }

  if (objectType === "TRIGGER") {
    return `create or replace trigger ${qualifiedName}
before insert on ${toQuotedIdentifier(schema)}."YOUR_TABLE"
for each row
begin
  null;
end;
/`;
  }

  if (objectType === "SEQUENCE") {
    return `create sequence ${qualifiedName}
  start with 1
  increment by 1
  nocache;`;
  }

  if (objectType === "TYPE") {
    return `create or replace type ${qualifiedName} as object (
  id number
);
/`;
  }

  return `create or replace synonym ${qualifiedName}
for ${toQuotedIdentifier(schema)}."TARGET_OBJECT";`;
}
