import { describe, expect, it } from "vitest";
import {
  buildCreateObjectTemplate,
  createObjectDefaultName,
  normalizeCreateObjectName,
  normalizeCreateObjectType,
} from "./createObjectTemplates";

describe("createObjectTemplates", () => {
  it("normalizes supported object types case-insensitively", () => {
    expect(normalizeCreateObjectType(" table ")).toBe("TABLE");
    expect(normalizeCreateObjectType("PACKAGE BODY")).toBe("PACKAGE BODY");
    expect(normalizeCreateObjectType("unknown")).toBeNull();
  });

  it("falls back to NEW_OBJECT for unsupported default names", () => {
    expect(createObjectDefaultName("unknown")).toBe("NEW_OBJECT");
  });

  it("normalizes object names into valid Oracle identifiers", () => {
    expect(normalizeCreateObjectName("TABLE", " 1 invalid name ")).toBe(
      "_1_INVALID_NAME",
    );
  });

  it("builds a table template with normalized quoted identifiers", () => {
    const template = buildCreateObjectTemplate({
      schema: 'my"schema',
      objectType: "table",
      objectName: 'orders"2026',
    });

    expect(template).toContain('create table "MY_SCHEMA"."ORDERS_2026"');
    expect(template).toContain(
      "id number generated by default as identity primary key",
    );
  });

  it("throws for unsupported object types", () => {
    expect(() =>
      buildCreateObjectTemplate({
        schema: "app",
        objectType: "materialized view",
        objectName: "mv_sales",
      }),
    ).toThrow("Unsupported object type");
  });

  it("builds templates for every supported object type", () => {
    const cases: Array<{ objectType: string; expectedSnippet: string }> = [
      { objectType: "VIEW", expectedSnippet: "create or replace view" },
      { objectType: "PROCEDURE", expectedSnippet: "create or replace procedure" },
      { objectType: "FUNCTION", expectedSnippet: "create or replace function" },
      { objectType: "PACKAGE", expectedSnippet: "create or replace package " },
      { objectType: "PACKAGE BODY", expectedSnippet: "create or replace package body" },
      { objectType: "TRIGGER", expectedSnippet: "create or replace trigger" },
      { objectType: "SEQUENCE", expectedSnippet: "create sequence" },
      { objectType: "TYPE", expectedSnippet: "create or replace type" },
      { objectType: "SYNONYM", expectedSnippet: "create or replace synonym" },
    ];

    for (const testCase of cases) {
      const template = buildCreateObjectTemplate({
        schema: "app",
        objectType: testCase.objectType,
        objectName: "demo_obj",
      });

      expect(template).toContain(testCase.expectedSnippet);
      expect(template).toContain('"APP"."DEMO_OBJ"');
    }
  });
});
